# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testin        
name: .NET

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DB_DATABASE: test_db
      DB_USER: root
      DB_PASSWORD: root
      TestUser: ${{secrets.MYSQL_USERNAME}}
      TestPassword: ${{secrets.MYSQL_PASSWORD}})}}
    steps:
    - uses: actions/checkout@v4
    - run: sudo /etc/init.d/mysql start
    - run: mysql -e "CREATE USER '$TestUser'@'localhost' IDENTIFIED WITH caching_sha2_password BY '$TestPassword';" -u$DB_USER -p$DB_PASSWORD
      
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
