# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
            - name: Start MySQL
  # You may pin to the exact commit or the version.
  # uses: samin/mysql-action@4dd1210f1d6b9c2468adec44066ef4a97b8f07f3
  on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]
  steps:
  uses: samin/mysql-action@v1.3
  with:
    # The port of host
    host port: # optional, default is 3306
    # The port of container
    container port: # optional, default is 3306
    # --character-set-server - The character set of MySQL server
    character set server: # optional, default is utf8mb4
    # --collation-server - The character collation of MySQL server
    collation server: # optional, default is utf8mb4_general_ci
    # Version of MySQL to use
    mysql version: # optional, default is latest
    # MYSQL_ROOT_PASSWORD - root superuser password
    mysql root password: # optional, default is 
    # MYSQL_DATABASE - name for the default database that is created
    mysql database: # optional, default is 
    # MYSQL_USER - create the specified user with superuser power for created database
    mysql user: # optional, default is 
    # MYSQL_PASSWORD - specified superuser password which user is power for created database
    mysql password: # optional, default is 
          
name: .NET

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
