# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testin        
name: .NET

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DB_HOST: 127.0.0.1
      DB_CONNECTION: mysql
      DB_DATABASE: test
      DB_PORT: ${{ job.services.mysql.ports[3306] }}
      DB_USER: ${{ secrets.MYSQL_USERNAME }}
      DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
    steps:
    - uses: actions/checkout@v4
    - name: Start MySQL
      run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u$DB_USER -p$DB_PASSWORD
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
